language: bash
services: 
  - docker

matrix:
  include:
    - env: VERSION=5.4 VARIANT=fpm FLAVOR=coffe
    - env: VERSION=5.6 VARIANT=fpm FLAVOR=peach
    

script: 
  - "docker build -t 'mandic/php:${VERSION}-${VARIANT}-${FLAVOR}' ${VERSION}-${VARIANT}/${FLAVOR}"

after_script:
  - docker images