sudo: required
group: edge
dist: trusty
language: bash
services:
- docker
matrix:
  include:
  - env: VERSION=5.3 VARIANT=fpm FLAVOR=garlic
  - env: VERSION=5.3 VARIANT=fpm FLAVOR=oyster
  - env: VERSION=5.3 VARIANT=fpm FLAVOR=oyster-nr
  - env: VERSION=5.3 VARIANT=fpm FLAVOR=oyster-apc
  - env: VERSION=5.3 VARIANT=fpm FLAVOR=coconut
  - env: VERSION=5.4 VARIANT=fpm FLAVOR=coffe
  - env: VERSION=5.6 VARIANT=fpm FLAVOR=peach
  - env: VERSION=5.6 VARIANT=fpm FLAVOR=bacon
  - env: VERSION=5.6 VARIANT=fpm FLAVOR=rice
  - env: VERSION=5.6 VARIANT=fpm FLAVOR=rice-nr
  - env: VERSION=7.0 VARIANT=fpm FLAVOR=cherry
  - env: VERSION=7.0 VARIANT=fpm FLAVOR=cherry-nr
  - env: VERSION=7.1 VARIANT=fpm FLAVOR=mango
  - env: VERSION=7.1 VARIANT=fpm FLAVOR=mango-nr
  - env: VERSION=7.2 VARIANT=fpm FLAVOR=ripple
  - env: VERSION=7.2 VARIANT=fpm FLAVOR=ripple-nr
install:
- docker build -t "mandic/php:${VERSION}-${VARIANT}-${FLAVOR}" ${VERSION}-${VARIANT}/${FLAVOR}
script:
- docker images
env:
  global:
  - secure: eA00D6qDuEWUVLDy3/gR4jhb97fwtWxdgTtrm63dnx6I8uB17olu/LenT0UbQgX5iYm7fnME4TYZc/VLMlDHMD+KPakAEepIS5p+aUh/iaHslih7OjYVnR6xPBsg6mOHUD5pe6OPpG/3iaoxSKe3zgbbm3pKxXNGXu+fP2DW3OoaADiTmwxfXz0oV9Ff/COtpzzPLqxLMPItKQDzz2CeRm+xLBouKRgT5gUq8kP5ifeuDZ08bEekIpiPfOQqbH7NDKOPPYQ2SRPyYzOUlVMtSmOaq7NRO8EuonIGntKRAseobSW/8+RY0WuRN/YsQGdQLfxOEP4iBVogZ03OCejymwQLYKofuJF2SCypXbfhtNR6ABHGEklQI5lTMAiqyNxG9MCMTze2m5c6jFRR2BBwTcD62I54TjEENzhIaOZILcg4/RPapV52hj143zkLTFoMT2oDPHMM8UEGnYlCM9zyT5P/jUrTEPBj8qbHH21Y1ne2TEAqFytcty/OI1qcJe0hsc/DUeFaoUbnJaZ5mt5Ndfbk35oq7MjiXp3EZKVbqPeGrvfgpn3Hde+y+N4P8DQaXVSnSQbzxCXMxWvjF6l/0KbZ4RT0UniKgniCsDgGyLD88MTlISZz2xOavSkdwupkcTTZpgOAx0+eUaLaw6CDD1Bkh80F3KRAiLJ0qUPeFNk=
  - secure: mvR3aV3goP5tCDTZWgx2N++1DCMXsp9acAuLlPrGyvPrqffpIJiXNnS2PDvwHtodU/VxrlZjPotKsxlLwvNK58FNzDd4t8sNCESJ4wACpbFDYjusH+5O685yvW6lcvYE/qsQJK2yYP8rY1guILaNWCZ/IaBc8MI7dNNk7AxeHvTv7k28lrdfxqSuPMkXbWKJeO8EahnZ43ywXKib3gETr/L1noqYkDMEvPh7mb9XMgpGjwzB8gA2PSNpWqbBwGuRjZUycV3vZ8M5lkw2JtANB2DCQuvaQzaSD7CGgQKyJo+yLhe+Y+prkON7ex6ycn3h1H1LOz/GGMl7dmarepAIx0bbFmE6dE4khYoAy413x/gjoepc4JDHDjt25liTsMpq3Ili5ugy44ExLb0R+wj+to4JPdcV47LS/2epwXbvpmLd5t0e9HwU4iQiyCYJ1eGIokwEOdgGTH8HkAK5NnYQuh42C2QeSpKDB+4nPHxMczi+O//BxkiBIsnGmqsrtGnnAIeVLmKWEjVkyoqkGrFYoCzIayCuoIWfHbsKEskdvhxvMtpzNzf/QmKU8/CazdBogAGZx7ffVzV5wWuQtSGZiZeOp6w6zqxPOy424PWb2JgVg5Ev2joKs5OES3jNYRTu5ap+4bEESd+bL0UDcv/WD3/7hk/tx+h4sTBuxi8INRU=
  - secure: IQuReTzyboZm1pXG013kFoxvAZM8c81CLuNvrZoN0svim7ktRQo314vIWJ98a1JmsMVfvVuoZyarDe+qKJvdWvwx4yyuV5kMruOZcvum5pqrGs6HIB38BCjw60M2Sn93hbvsijv1vc96V7/gNFY64Tj1sGqYWAYv3wtCFEpRKo3Uyc2x3dH+Z+/BcmPa+NJt0tDMNHGz6UvFnNbm8I3hh4Ku9ksNHGn6ulXWrWLtuCJtIuxO+SpPpZwJb/cvlacRwG70qzj+RvROkP/GbDkAPcc+XMbcqhbs9UinNKwfrTnnRlBQv3pFRb4uJUsBIdPLaXFhrTnUg+uMPLmIArVxhTOHwx7Tf3WhN4IaeG6eh+2ZYmZE6p3xx2miKhWP/QPjp2WWmOaMuTmGWn+cajoqLfp3zwc9r9vDEVG+sNg/xf5oOYuz+Z604Q6LxWJVXbrSxl98TUnFqEjXsvEvPAObtc1VhhzewCmps0E0K5KdxJBFheY+wfvjnAYgNEVv8mVohd3HvgT/Apm5KYCun+enKWadSTDD7//BjSIX7jE2iK3s+Npc0YytcDAtJQ682QLrRnvmgmSU01TZT5cYJwF0F4ZWIYEK2pdWCkTy9ALWQChKgup57LO63MIrsOdSgMjuvO/QD1Xjw0q3IHhD/ySbYMrHx1XWH1GASn/vPu4pKJQ=
after_success:
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  - docker push mandic/php:${VERSION}-${VARIANT}-${FLAVOR}